server:
  port: 8010
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false  #表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
    fetchRegistry: false       #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    serviceUrl:
      defaultZone: http://discovery:8010/eureka/   #可以配置多个地址，用逗号“,”分割
security:
  basic:
    enabled: false
  user:
    name: listening
    password: 123456
