server:
  port: 8010
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8010/eureka/